repos:
  - repo: https://github.com/hadolint/hadolint
    rev: v2.15.1
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.97.1
    hooks:
      - id: trufflehog

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 44.103.6 # can't match with renovate container
    hooks:
      - id: renovate-config-validator
        files: ^renovate\.json$
