name: Docker Runner
on:
  push:
    branches: [main]
    paths:
      - 'docker/Dockerfile'
      - 'docker/VERSION'
      - '.forgejo/workflows/docker-runner.yml'
      - '.forgejo/workflows/_build-scan-push.yml'
  schedule:
    - cron: '00 8 * * 1'
      timezone: Europe/London
  workflow_dispatch:
concurrency:
  group: build-docker-runner-${{ github.ref }}
  cancel-in-progress: false
jobs:
  build:
    uses: ./.forgejo/workflows/_build-scan-push.yml
    with:
      dockerfile-context: docker
      image-tag-var: ${{ vars.DOCKER_RUNNER }}
    secrets: inherit
